-- Utebo en Fiestas · Esquema Supabase
-- Ejecutar en SQL Editor de un proyecto nuevo.

create table if not exists public.events (
  id text primary key,
  date date not null,
  start time not null,
  "end" time,
  title text not null,
  location text not null,
  category text not null,
  audience text[] not null default '{}',
  description text,
  status text not null default 'scheduled' check (status in ('scheduled', 'rescheduled', 'cancelled')),
  time_tbd boolean not null default false,
  is_featured boolean not null default false,
  source text,
  updated_at timestamptz not null default now()
);

alter table public.events add column if not exists time_tbd boolean not null default false;

create table if not exists public.announcements (
  id text primary key,
  level text not null default 'info' check (level in ('info', 'warning', 'urgent', 'success')),
  title text not null,
  message text not null,
  active boolean not null default true,
  starts_at timestamptz,
  ends_at timestamptz,
  updated_at timestamptz not null default now()
);

create table if not exists public.analytics_events (
  id bigint generated by default as identity primary key,
  event_type text not null,
  event_id text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists events_date_start_idx on public.events (date, start);
create index if not exists announcements_active_idx on public.announcements (active, updated_at desc);
create index if not exists analytics_created_at_idx on public.analytics_events (created_at desc);

alter table public.events enable row level security;
alter table public.announcements enable row level security;
alter table public.analytics_events enable row level security;

drop policy if exists "events_public_read" on public.events;
create policy "events_public_read" on public.events for select to anon, authenticated using (true);

drop policy if exists "announcements_public_read" on public.announcements;
create policy "announcements_public_read" on public.announcements for select to anon, authenticated using (true);

drop policy if exists "events_admin_insert" on public.events;
create policy "events_admin_insert" on public.events for insert to authenticated with check (true);
drop policy if exists "events_admin_update" on public.events;
create policy "events_admin_update" on public.events for update to authenticated using (true) with check (true);
drop policy if exists "events_admin_delete" on public.events;
create policy "events_admin_delete" on public.events for delete to authenticated using (true);

drop policy if exists "announcements_admin_insert" on public.announcements;
create policy "announcements_admin_insert" on public.announcements for insert to authenticated with check (true);
drop policy if exists "announcements_admin_update" on public.announcements;
create policy "announcements_admin_update" on public.announcements for update to authenticated using (true) with check (true);
drop policy if exists "announcements_admin_delete" on public.announcements;
create policy "announcements_admin_delete" on public.announcements for delete to authenticated using (true);

drop policy if exists "analytics_public_insert" on public.analytics_events;
create policy "analytics_public_insert" on public.analytics_events for insert to anon, authenticated with check (true);
drop policy if exists "analytics_admin_read" on public.analytics_events;
create policy "analytics_admin_read" on public.analytics_events for select to authenticated using (true);

do $$
begin
  alter publication supabase_realtime add table public.events;
exception when duplicate_object then null;
end $$;

do $$
begin
  alter publication supabase_realtime add table public.announcements;
exception when duplicate_object then null;
end $$;
